### ISSUE TITLE
Consistent language

### ISSUE THREAD

**Issue by lauren-walker** [welsh-revenue-authority/visitor-levy-prototypes#1]
https://welsh-revenue-authority.github.io/visitor-levy-prototypes/start

Should read 'register visitor accommodation providers'

**Comment by lauren-walker** [comment]
https://welsh-revenue-authority.github.io/visitor-levy-prototypes/home

Are we going to refer to Cardiff here, or use a made-up county?

Make sure it is always 'visitor accommodation' and 'visitor accommodation providers'.

**Comment by lauren-walker** [comment]
https://welsh-revenue-authority.github.io/visitor-levy-prototypes/add-account

Change 'accountant' to 'agent'

**Comment by lauren-walker** [comment]
https://welsh-revenue-authority.github.io/visitor-levy-prototypes/add-account

The writing in the green box currently doesn't make sense - you might still be working on this though.

**Comment by jakereal** [comment]
Fixed with commit 13cce36641909f63748398052b646e3e3d385c2c
