### ISSUE TITLE
Snag list #2

### ISSUE THREAD

**Issue by HarryTrimble** [welsh-revenue-authority/visitor-levy-prototypes#14]
Firstly, Jake, well done on the UI refactoring so far. A big improvement already. 

- [x] Remove 'Sign in' button from heading - as it doesn't mak
- [x] Change header to background-color: #F8D756; - moving away from the gov.wales grey header and branding means we can experiment more without  worrying people who's job it is to preserve a consistent welsh gov online brand. 
- [x] Make header say '[Prototype] This is not a real service' - from my experience, people outside of digital teams, don't know what 'prototype' means by itself. 
- [x] reduce v-container class' top-margin from 96px to 40px
- [x] #16
- [x] #18
- [x] #19
- [x] Is there anything we can do about the latency / load time for elements on a page. It takes half a second to load and my guess this might reduce a users confidence in the service. 
- [x] Make desk-top container default width 960px 
- [x] Is there anyway we could add an [autocomplete component](https://alphagov.github.io/accessible-autocomplete/) - I think we could use it for someone [searching for company details ](https://visitor-levy-56b6e0ca8144.herokuapp.com/en/register/search-company-details)
- [x] #17

**Comment by jakereal** [comment]
- Sidebar wrapping

**Comment by jakereal** [comment]
> * Is there anyway we could add an [autocomplete component](https://alphagov.github.io/accessible-autocomplete/) - I think we could use it for someone [searching for company details ](https://visitor-levy-56b6e0ca8144.herokuapp.com/en/register/search-company-details)

Moved to new issue, #15

**Comment by jakereal** [comment]
> > * Is there anyway we could add an [autocomplete component](https://alphagov.github.io/accessible-autocomplete/) - I think we could use it for someone [searching for company details ](https://visitor-levy-56b6e0ca8144.herokuapp.com/en/register/search-company-details)
> 
> Moved to new issue, #15

Completed in issue #15

**Comment by jakereal** [comment]
>  Is there anything we can do about the latency / load time for elements on a page. It takes half a second to load and my guess this might reduce a users confidence in the service.

I've looked at removing animation. 

2 options for this:
- Reduce transition animation - Can make it look faster
- Remove transition - Been mentioned that people sometimes found it difficult to see the difference between pages without a transition animation to break it up

**Comment by jakereal** [comment]
> - [x] Remove 'Sign in button'
> - [x] Change header to background-color: #F8D756; - moving away from the gov.wales grey header and branding means we can experiment more without worrying people who's job it is to preserve a consistent Welsh gov online brand.
> - [x] Make header say '[Prototype] This is not a real service' - from my experience, people outside of digital teams, don't know what 'prototype' means by itself.
> - [x] Reduce v-container class' top-margin from 96px to 40px
> - [x] Make forms two-thirds wide - same reason as the last point about readability.

Added in 084d1f7

**Comment by jakereal** [comment]
> Make desktop container width to 960px

Large screen layouts have been improved.

Emails have been changed, I change the service pages to a similar layout to them if the above changes aren't sufficient.

**Comment by jakereal** [comment]
> * [x]  [Matching Prototype Journeys #17](https://github.com/welsh-revenue-authority/visitor-levy-prototypes/issues/17)

Moved to the new issue
