### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by lauren-walker** [welsh-revenue-authority/visitor-levy-prototypes#2]
https://welsh-revenue-authority.github.io/visitor-levy-prototypes/registration

<img width="591" alt="image" src="https://github.com/welsh-revenue-authority/visitor-levy-prototypes/assets/157797568/085c3e38-80c0-4ab3-990c-5f03b130b735">

Should be 'Companies House' not 'Company house'. 

I don't think it will be important yet but international companies might not have a CH number, a partnership doesn't fall into any of the categories we have provided and if they went down this route also may not have a CH number - might need an option for 'other' or to proceed without CH number.

**Comment by lauren-walker** [comment]
https://welsh-revenue-authority.github.io/visitor-levy-prototypes/add-account

The writing in the green box currently doesn't make sense - you might still be working on this though.

**Comment by lauren-walker** [comment]
https://welsh-revenue-authority.github.io/visitor-levy-prototypes/consult-email

Please remove any reference to a tourist tax - it is not a tax and is not just for tourists. 

Thanks for changing it to a fake LA but it does still say Cardiff at the bottom, to flag.

**Comment by lauren-walker** [comment]
https://welsh-revenue-authority.github.io/visitor-levy-prototypes/intro-email

Please reference a 'levy' not a tax - it is not a tax

**Comment by jakereal** [comment]
> https://welsh-revenue-authority.github.io/visitor-levy-prototypes/consult-email
> 
> Please remove any reference to a tourist tax - it is not a tax and is not just for tourists.
> 
> Thanks for changing it to a fake LA but it does still say Cardiff at the bottom, to flag.

> https://welsh-revenue-authority.github.io/visitor-levy-prototypes/intro-email
> 
> Please reference a 'levy' not a tax - it is not a tax. Also should read 'visitor levy collected' rather than 'collected visitor levies'.

Fixed with commit 28f3837591d4cb7f6d558d8fb590d9426ad67033

**Comment by jakereal** [comment]
> https://welsh-revenue-authority.github.io/visitor-levy-prototypes/registration
> 
> <img alt="image" width="591" src="https://private-user-images.githubusercontent.com/157797568/300497162-085c3e38-80c0-4ab3-990c-5f03b130b735.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NjcwNzksIm5iZiI6MTcwNjg2Njc3OSwicGF0aCI6Ii8xNTc3OTc1NjgvMzAwNDk3MTYyLTA4NWMzZTM4LTgwYzAtNGFiMy05OTBjLTVmMDNiMTMwYjczNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwOTM5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZGI4OWY0M2E4Mjc1ZTQ4YzUwYTVhMDBjMzc5Mjg1N2EyZTNiODlkNDk4ZTk2NWRkODc2MDQ5OTU1NTMyNTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B1J8iKl9DO8zlOHPmyoZAg0HP2LMeX1NphPNLL9rU1k">
> Should be 'Companies House' not 'Company house'.
> 
> I don't think it will be important yet but international companies might not have a CH number, a partnership doesn't fall into any of the categories we have provided and if they went down this route also may not have a CH number - might need an option for 'other' or to proceed without CH number.

Moved to commit #4
