### ISSUE TITLE
Ash Comments

### ISSUE THREAD

**Issue by CaddickA** [welsh-revenue-authority/visitor-levy-prototypes#5]
**Registration flow :** UR suggests we need to tweak the language. 
- How about we try "How many accommodation **sites** have you got to register?"
- Can we allow multiple types of accomodation to be checked? 
- Can we hide the VL payments being on the home page for the time being or at least greyed out until after someone has registered? 

One of the goals is to articulate how the service looks over time, so I wonder Jake in the next sprint you do surface 2 prototypes. First get the basic version of day 1 out of the way and clean it up like you've been doing -  where you new people come in and register for the first time. 
the second one would be an iteration of what you've currently got showing how it could look after 450 days where VL is coming in or live etc, alongside showing how to register and de-register etc. 

**E-mail**
VL starts soon - add a line to say "Find out more about visitor levy and your obligations here"(blank link etc). Can we also change the days to be 365 days.

**Comment by jakereal** [comment]
> One of the goals is to articulate how the service looks over time, so I wonder Jake in the next sprint you do surface 2 prototypes. First get the basic version of day 1 out of the way and clean it up like you've been doing - where you new people come in and register for the first time. the second one would be an iteration of what you've currently got showing how it could look after 450 days where VL is coming in or live etc, alongside showing how to register and de-register etc.

Handled in #6,

**Comment by jakereal** [comment]
> How about we try "How many accommodation sites have you got to register?"

Fixed by fee7b53

> Can we allow multiple types of accommodation to be checked?

Added in fee7b53

> Can we hide the VL payments being on the home page for the time being or at least greyed out until after someone has registered?

Added in fee7b53
